package entities;
// Generated 17-nov-2017 10:05:11 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas implements java.io.Serializable {

	private Integer codigo;
	private String titulo;
	private Date fecha;
	private double presupuesto;
	private Set actoreses = new HashSet(0);

	public Peliculas() {
	}

	public Peliculas(String titulo, Date fecha, double presupuesto) {
		this.titulo = titulo;
		this.fecha = fecha;
		this.presupuesto = presupuesto;
	}

	public Peliculas(String titulo, Date fecha, double presupuesto, Set actoreses) {
		this.titulo = titulo;
		this.fecha = fecha;
		this.presupuesto = presupuesto;
		this.actoreses = actoreses;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public double getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(double presupuesto) {
		this.presupuesto = presupuesto;
	}

	public Set getActoreses() {
		return this.actoreses;
	}

	public void setActoreses(Set actoreses) {
		this.actoreses = actoreses;
	}

}
